# Generated by Django 5.2.10 on 2026-01-13 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('website', models.URLField()),
                ('logo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPUSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(blank=True, max_length=100)),
                ('memory_size', models.CharField(blank=True, max_length=20)),
                ('memory_type', models.CharField(blank=True, max_length=20)),
                ('memory_bus', models.CharField(blank=True, max_length=20)),
                ('base_clock', models.CharField(blank=True, max_length=50)),
                ('boost_clock', models.CharField(blank=True, max_length=50)),
                ('interface', models.CharField(blank=True, max_length=50)),
                ('power_connector', models.CharField(blank=True, max_length=100)),
                ('tdp', models.CharField(blank=True, max_length=20)),
                ('recommended_psu', models.CharField(blank=True, max_length=20)),
                ('hdmi_ports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('displayport_ports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=30)),
                ('slots', models.CharField(blank=True, max_length=10)),
                ('cuda_cores', models.CharField(blank=True, max_length=20)),
                ('stream_processors', models.CharField(blank=True, max_length=20)),
                ('ray_tracing', models.BooleanField(blank=True, null=True)),
                ('dlss_support', models.BooleanField(blank=True, null=True)),
                ('fsr_support', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specs', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='products.category')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='products.retailer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-order'), ('upcoming', 'Upcoming')], default='in_stock', max_length=20)),
                ('product_url', models.URLField(max_length=1000)),
                ('is_available', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.retailer')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('product', 'retailer')},
            },
        ),
    ]
