import { ComponentConfig } from "@/types/builder"

export const COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    category: "CPU",
    label: "Processor",
    icon: "Cpu",
    required: true,
    maxSlots: 3,
    allowQuantity: false,
    description: "The brain of your computer",
  },
  {
    category: "Motherboard",
    label: "Motherboard",
    icon: "CircuitBoard",
    required: true,
    maxSlots: 1,
    allowQuantity: false,
    description: "Connects all your components",
  },
  {
    category: "RAM",
    label: "Memory (RAM)",
    icon: "MemoryStick",
    required: true,
    maxSlots: 3,
    allowQuantity: true,
    description: "System memory for multitasking",
  },
  {
    category: "Storage",
    label: "Storage",
    icon: "HardDrive",
    required: true,
    maxSlots: 3,
    allowQuantity: false,
    description: "Store your files and programs",
  },
  {
    category: "GPU",
    label: "Graphics Card",
    icon: "MonitorPlay",
    required: false,
    maxSlots: 3,
    allowQuantity: false,
    description: "For gaming and graphics work",
  },
  {
    category: "PSU",
    label: "Power Supply",
    icon: "Zap",
    required: true,
    maxSlots: 1,
    allowQuantity: false,
    description: "Powers your system",
  },
  {
    category: "Case",
    label: "Case",
    icon: "Box",
    required: true,
    maxSlots: 1,
    allowQuantity: false,
    description: "Houses all components",
  },
  {
    category: "Cooler",
    label: "CPU Cooler",
    icon: "Fan",
    required: false,
    maxSlots: 3,
    allowQuantity: false,
    description: "Keeps your CPU cool",
  },
  {
    category: "Monitor",
    label: "Monitor",
    icon: "Monitor",
    required: false,
    maxSlots: 3,
    allowQuantity: false,
    description: "Display for your system",
  },
]

export const SHOPS = [
  { name: "Star Tech" as const },
  { name: "Techland" as const },
  { name: "Potaka IT" as const },
  { name: "Skyland" as const },
  { name: "Ryans" as const },
]
