"""
Hardware detection patterns for normalizers.

This package contains pre-compiled regex patterns and mappings
for extracting compatibility attributes from PC components.
"""

from .cpu_patterns import (
    SOCKET_PATTERNS as CPU_SOCKET_PATTERNS,
    GENERATION_MAP,
    SOCKET_SPEC_KEYS as CPU_SOCKET_SPEC_KEYS,
    TDP_SPEC_KEYS,
    AMD_BRAND_INDICATORS,
    INTEL_BRAND_INDICATORS,
    normalize_socket,  # Utility function for socket normalization
)

from .motherboard_patterns import (
    SOCKET_PATTERNS as MOBO_SOCKET_PATTERNS,
    CHIPSET_TO_SOCKET,
    CHIPSET_TO_DDR,
    CHIPSET_PATTERN,
    FORM_FACTOR_PATTERNS,
    SOCKET_SPEC_KEYS as MOBO_SOCKET_SPEC_KEYS,
    CHIPSET_SPEC_KEYS,
    FORM_FACTOR_SPEC_KEYS,
    MEMORY_TYPE_SPEC_KEYS as MOBO_MEMORY_TYPE_SPEC_KEYS,
    MEMORY_SLOTS_SPEC_KEYS,
    MEMORY_SPEED_SPEC_KEYS as MOBO_MEMORY_SPEED_SPEC_KEYS,
    MEMORY_CAPACITY_SPEC_KEYS as MOBO_MEMORY_CAPACITY_SPEC_KEYS,
    MOTHERBOARD_BRANDS,
    PRODUCT_LINES,
    WIFI_FEATURES,
    STRIP_WORDS,
)

from .ram_patterns import (
    DDR_PATTERNS,
    SPEED_PATTERNS,
    KIT_CAPACITY_PATTERN,
    SIMPLE_CAPACITY_PATTERN,
    MODULE_COUNT_PATTERNS,
    MEMORY_TYPE_SPEC_KEYS as RAM_MEMORY_TYPE_SPEC_KEYS,
    MEMORY_SPEED_SPEC_KEYS as RAM_MEMORY_SPEED_SPEC_KEYS,
    MEMORY_CAPACITY_SPEC_KEYS as RAM_MEMORY_CAPACITY_SPEC_KEYS,
    MEMORY_MODULES_SPEC_KEYS,
    DDR5_MIN_SPEED,
    DDR4_MIN_SPEED,
    DDR4_MAX_SPEED,
)

__all__ = [
    # CPU
    "CPU_SOCKET_PATTERNS",
    "GENERATION_MAP",
    "CPU_SOCKET_SPEC_KEYS",
    "TDP_SPEC_KEYS",
    "AMD_BRAND_INDICATORS",
    "INTEL_BRAND_INDICATORS",
    "normalize_socket",  # Utility function
    # Motherboard
    "MOBO_SOCKET_PATTERNS",
    "CHIPSET_TO_SOCKET",
    "CHIPSET_TO_DDR",
    "CHIPSET_PATTERN",
    "FORM_FACTOR_PATTERNS",
    "MOBO_SOCKET_SPEC_KEYS",
    "CHIPSET_SPEC_KEYS",
    "FORM_FACTOR_SPEC_KEYS",
    "MOBO_MEMORY_TYPE_SPEC_KEYS",
    "MEMORY_SLOTS_SPEC_KEYS",
    "MOBO_MEMORY_SPEED_SPEC_KEYS",
    "MOBO_MEMORY_CAPACITY_SPEC_KEYS",
    "MOTHERBOARD_BRANDS",
    "PRODUCT_LINES",
    "WIFI_FEATURES",
    "STRIP_WORDS",
    # RAM
    "DDR_PATTERNS",
    "SPEED_PATTERNS",
    "KIT_CAPACITY_PATTERN",
    "SIMPLE_CAPACITY_PATTERN",
    "MODULE_COUNT_PATTERNS",
    "RAM_MEMORY_TYPE_SPEC_KEYS",
    "RAM_MEMORY_SPEED_SPEC_KEYS",
    "RAM_MEMORY_CAPACITY_SPEC_KEYS",
    "MEMORY_MODULES_SPEC_KEYS",
    "DDR5_MIN_SPEED",
    "DDR4_MIN_SPEED",
    "DDR4_MAX_SPEED",
]
